//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TtyhLauncher.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TtyhLauncher.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string RunError {
            get {
                return ResourceManager.GetString("RunError", resourceCulture);
            }
        }
        
        public static string DownloadVersionError {
            get {
                return ResourceManager.GetString("DownloadVersionError", resourceCulture);
            }
        }
        
        public static string VersionIndexesCorrupted {
            get {
                return ResourceManager.GetString("VersionIndexesCorrupted", resourceCulture);
            }
        }
        
        public static string FailedToCheckVersion {
            get {
                return ResourceManager.GetString("FailedToCheckVersion", resourceCulture);
            }
        }
        
        public static string FailedToFetchIndexes {
            get {
                return ResourceManager.GetString("FailedToFetchIndexes", resourceCulture);
            }
        }
        
        public static string FailedToUpdateProfile {
            get {
                return ResourceManager.GetString("FailedToUpdateProfile", resourceCulture);
            }
        }
        
        public static string FailedToLogin {
            get {
                return ResourceManager.GetString("FailedToLogin", resourceCulture);
            }
        }
        
        public static string ProfileDoesNotExist {
            get {
                return ResourceManager.GetString("ProfileDoesNotExist", resourceCulture);
            }
        }
        
        public static string NoVersionsAvailable {
            get {
                return ResourceManager.GetString("NoVersionsAvailable", resourceCulture);
            }
        }
        
        public static string FailedToBecomeOnline {
            get {
                return ResourceManager.GetString("FailedToBecomeOnline", resourceCulture);
            }
        }
        
        public static string CantDeleteProfile {
            get {
                return ResourceManager.GetString("CantDeleteProfile", resourceCulture);
            }
        }
    }
}
